---
title: "streams_puertorico"
author: "zachyloo"
format: html
editor: visual
execute: 
  warning: false
---

```{r}
library(tidyverse)
# source and load cleaned data
streams_long <- read_csv(here::here("data/streams_clean.csv"))
# source in moving_avg function
source(here::here("R", "moving_avg_function.R"))
# source in zapply function
source(here::here("R", "zapply.R"))

```

```{r}
library(patchwork)

p1 <- ggplot(streams_long, aes(x = sample_date, color = sample_id)) +
  geom_line(aes(y = k_rolling)) +
  scale_color_brewer(palette = "Dark2") +
  labs(y = "K") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "none") 

p2 <- ggplot(streams_long, aes(x = sample_date, color = sample_id)) +
  geom_line(aes(y = no3_n_rolling)) +
  scale_color_brewer(palette = "Dark2") +
  labs(y = "NO3") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "none")

p3 <- ggplot(streams_long, aes(x = sample_date, color = sample_id)) +
  geom_line(aes(y = mg_rolling)) +
  scale_color_brewer(palette = "Dark2") +
  labs(y = "Mg") +
  labs(color = "Stream ID") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

p4 <- ggplot(streams_long, aes(x = sample_date, color = sample_id)) +
  geom_line(aes(y = ca_rolling)) +
  scale_color_brewer(palette = "Dark2") +
  labs(y = "Ca") +
  theme_minimal() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "none")

p5 <- ggplot(streams_long, aes(x = sample_date, color = sample_id)) +
  geom_line(aes(y = nh4_n_rolling)) +
  scale_color_brewer(palette = "Dark2") +
  labs(y = "NH4",
       x = "Sample Date") +
  theme_minimal() +
  theme(legend.position = "none")

plots <- (p1 / p2 / p3 / p4 / p5)
plots + plot_annotation(
  title = "Chemistry of streams from the Luquillo Mountains",
  subtitle = "Post Hurricane Hugo (1989)",
  caption = "Data retrived from: McDowell, W. and International Institute of Tropical Forestry(IITF), USDA Forest Service.. 2024."
)
```
